using System;
using Discord.WebSocket;
using Discord.Commands;
using Discord;
using System.Threading.Tasks;
using System.Reflection;


namespace PhoenixBot
{
    class CommandHandler
    {
        DiscordSocketClient _client { get;  set; }
        CommandService _service { get; set; }
        IServiceProvider _provider { get; set; }


        private ulong GuildId_ = Config.bot.guildID;
        private ulong eventChannelID = ChannelIds.channels.eventID;

        public async Task InitializeAsynce(DiscordSocketClient client, IServiceProvider serviceProvider)
        {
            _client = client;
            _service = new CommandService();
            _provider = serviceProvider;
            await _service.AddModulesAsync(Assembly.GetEntryAssembly(), _provider);
            _client.MessageReceived += PreCommandHandle;
            _client.UserJoined += UserJoined;
            _client.UserBanned += UserBanned;
            _client.UserLeft += UserLeft;
        }

        private Task UserBanned(SocketUser arg1, SocketGuild arg2)
        {
            try
            {
                var gAccount = Features.Games.UserAccounts.GameUserAccounts.GetAccount(arg1.Id);
                Features.Games.UserAccounts.GameUserAccounts.accounts.Remove(gAccount);
                Features.Games.UserAccounts.GameUserAccounts.SaveAccounts();
                return Task.CompletedTask;
            }
            catch
            {
                throw;
            }
        }

        private Task UserLeft(SocketGuildUser arg)
        {
            try
            {
                var gAccount = Features.Games.UserAccounts.GameUserAccounts.GetAccount(arg.Id);
                Features.Games.UserAccounts.GameUserAccounts.accounts.Remove(gAccount);
                Features.Games.UserAccounts.GameUserAccounts.SaveAccounts();
                return Task.CompletedTask;
            }
            catch
            {
                throw;
            }
        }

        public async Task UserJoined(SocketGuildUser user)
        {
            var dataEmbed = new EmbedBuilder();
            dataEmbed.WithTitle("Data Collected and USED")
                .WithDescription("**Data is only collected from Discord!** This means all data used or collected comes from Discord or what is created by the bot itself! **This means health for the minigame, points, warnings and such!** The only thing I collect is the id created for the servers, **THIS IS NOT YOUR LOGIN ID! I REPEAT THIS INFO HAS NOTHING TO DO WITH YOU LOGGING IN TO DISCORD!** This is an ID string that lets servers know who you are generated by Discord. **By using my server you are agreeing to let me use the ulong ID string to help manage the server to keep it from being toxic and having mini-games you can play!");

            var dmChannel = await user.GetOrCreateDMChannelAsync();
            await dmChannel.SendMessageAsync($"{user}, welcome to Digital Phoenix! Please read the Rules channel." +
                $"If you represent a guild please enter `!Diplomat` in the joining channel. Thank you", false, dataEmbed.Build());
            DataAccess Db = new DataAccess();
            Db.AddUser(user.Id);

        }
        private async Task PreCommandHandle(SocketMessage s)
        {
            //DataAccess Db = new DataAccess();
            var msg = s as SocketUserMessage;
            //if (msg == null) return;
            //var context = new SocketCommandContext(_client, msg);
            //UserAccountModel model = new UserAccountModel();
            //model = Db.GetUser(context.User.Id);
            //// Mute check
            //if ((model.IsMuted == 1 && context.User.IsBot == false) || (model.IsMuted == 1 && context.Guild.OwnerId != context.User.Id))
            //{
            //    if (msg.Content.StartsWith("!Appeal mute") || msg.Content.StartsWith("!Appeal Mute") || msg.Content.StartsWith("!appeal mute") || msg.Content.StartsWith("!appeal Mute"))
            //    {
            //        await HandleCommandAsync(msg);
            //        await Task.Delay(1);
            //        //var newMsg = msg.Content.TrimStart((char)12);
            //        //await Appeal((SocketGuildUser)context.User, newMsg, context.Guild);
            //    }
            //    await context.Message.DeleteAsync();
            //    return;
            //}
            //if (context.User.IsBot) return;
            await HandleCommandAsync(msg);

        }
        private async Task HandleCommandAsync(SocketUserMessage msg)
        {
            var context = new SocketCommandContext(_client, msg);
            int argPos = 0;
            await _service.ExecuteAsync(context, argPos, _provider);
            /*if (Config.bot.devMode == true && context.User.Id != Config.bot.botOwnerID && msg.HasStringPrefix(Config.bot.cmdPrefix, ref argPos))
            {
                await context.Channel.SendMessageAsync("Sorry but this is a Dev bot. If my name does not have Dev in it please contact my owner.");
                return;
            }*/
            if (msg.HasStringPrefix(Config.bot.cmdPrefix, ref argPos))
            {
                var result = await _service.ExecuteAsync(context, argPos, _provider);

                if (!result.IsSuccess && result.Error != CommandError.UnknownCommand)
                {
                    await context.Channel.SendMessageAsync(result.ErrorReason);
                }
            }
        }
        private async Task Appeal(SocketGuildUser user, string newMsg, SocketGuild guild)
        {
            var embed = new EmbedBuilder();
            embed.WithTitle("Mute Appeal")
                .WithDescription($"{guild.Owner.Mention}: {user.Mention} is currently muted.")
                .AddField("Appeal Message:", newMsg);
            var dmChannel = await user.GetOrCreateDMChannelAsync();
            var logChannel = Global.Client.GetGuild(Config.bot.guildID).GetTextChannel(ChannelIds.channels.requestID);
            await logChannel.SendMessageAsync($"{user.Mention}", false, embed.Build());
            await dmChannel.SendMessageAsync("Please wait for the Guild Master to review your appeal. Messaging them will not help your case.");
        }
        /*private async Task FactPost(IGuild CurrentGuild)
        {
            string Post = Features.RandomFact.CallRandomFact();
            var embed = new EmbedBuilder();
            var channel = Global.Client.GetGuild(Config.bot.guildID).GetTextChannel(Config.bot.generalID);
            embed.WithTitle("Random Fact for the day")
                .WithDescription(Post);
            await channel.SendMessageAsync("", false, embed);
            return;
        }*/
    }
}
